config/routes.rb
Rails.application.routes.draw do

   resources :playlists

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlist_controller.rb
class PlaylistController

	def create
	end

	def new
	end

	def index
	end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

	def create
		@playlist = Playlist.new(playlist_params)
		@playlist.save
		redirect_to @playlist #goes to the show method

    def show
    	@playlist = Playlist.find(params[:id]) # Playlist.find(8)

    	respond_to do |format|
      		format.html # show.html.erb
      		format.json { render json: @playlist }
    	end
  	end

	end

	def new
		@playlist = Playlist.new
	end

	def index
		@playlists = Playlist.all
	end



  	def edit
  		@playlist = Playlist.find(params[:id])
  	end	

  	def update
  		@playlist = Playlist.find(params[:id])
     	@playlist.update_attributes(playlist_params)
    	redirect_to @playlist    
	  end

  	def destroy
  		@playlist = Playlist.find(params[:id])
   	 	@playlist.destroy
    	respond_to do |format|
      	format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      	format.json { head :no_content }
    	end
  	end

  	private
  	def playlist_params
  		params.require(:playlist).permit(:title, :link)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoPlaylist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Home', playlists_path %>
<br>

<%= yield %>

</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :link %><br>
		<%= f.text_field :link %>
	</div>
	    <%= f.check_box :_destroy, :as => :boolean, :label => "Delete?" %>

	<div>
		<%= f.submit %>
	</div>

<% end %>

<%= form_for @playlist, method: :delete do |f| %>
	<%= f.submit "Delete" %>
<% end %>

app/views/playlists/_playlist.html.erb
<tr>

    <td><%= playlist.title %></td>

    <td><%= raw playlist.link %></td>

</tr>

app/views/playlists/create.html.erb
<h1>Video Playlist</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <br>
      <th>Video</th>
    </tr>
  </thead>

  <tbody>

  <%= render :partial => 'playlist', :collection => @playlists %>



  </tbody>
</table>

<br>

<p> </p>

app/views/playlists/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |

<%= link_to 'Back', playlists_path %> |

app/views/playlists/index.html.erb
<%= link_to 'Add New Video Sucka!', new_playlist_path(@playlist) %>

<h1 align="center">Your Video Playlist</h1>

<style>
table, th, td {
    border: 3px solid gray;
    padding: 10px;
}
table {
    border-spacing: 10px;
}
</style>

<table>
	<col align="center">
	
  <thead>
    <tr>
      <th>Title</th>
      <br>
      <th>Video</th>
    </tr>
  </thead>

  <tbody>

  <%= render :partial => 'playlist', :collection => @playlists %>



  </tbody>
</table>

<br>

app/views/playlists/new.html.erb
<h1>Video Playlist</h1>

<%= render 'form' %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @playlist.title %>
</p>

<p>
  <strong>link:</strong>
  <%= raw @playlist.link %>
</p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>